version: '3.0'
services:
  backend:
    container_name: flask-app
    restart: always
    build:
      context: ./ 
      dockerfile: docker/app/Dockerfile
    expose: 
      - "4231"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  web:
    container_name: web-app
    restart: always
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports: 
      - "8080:80"
    volumes: 
      - ./data/filebase:/app/filebase
    depends_on: 
      - backend
