version: '3.0'
services:
  backend:
    container_name: flask-app
    restart: always
    build:
      context: ./ 
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    environment: 
      TZ: Asia/Shanghai
    expose: 
      - "4231"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - filebase-volumes:/app/data/filebase
  web:
    container_name: web-app
    restart: always
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports: 
      - "8080:80"
    volumes: 
      - filebase-volumes:/app/filebase
    depends_on: 
      - backend
volumes: 
  filebase-volumes:
