version: '3'
services:
  app:
    container_name: flask-app
    restart: always
    build:
      context: ./ 
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./app:/app
      - ./log:/app/log
  web:
    container_name: web-app
    restart: true
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports: 
      - "8101:8101"
    depends_on: 
      - app
