version: '3.9'
services:
  backend:
    container_name: flask-app
    restart: always
    build:
      context: ./ 
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    environment: 
      TZ: Asia/Shanghai
    ports: 
      - "4231:4231"
    volumes:
      - ./config:/app/config
      - ./database:/app/database
      - ./filebase:/app/filebase
      - ./log:/app/log
      - ./notebase:/app/notebase
  web:
    container_name: web-app
    restart: always
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports: 
      - "8080:80"
    volumes: 
      - ./filebase:/app/filebase
    depends_on: 
      - backend
