name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the SmartTodo App Image
      run: docker build . --file docker/app/Dockerfile --tag smart-todo-app:$(date +%s)
    - name: Build the SmartTodo Web Image
      run: docker build . --file docker/web/Dockerfile --tag smart-todo-web:$(date +%s)
