name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    env:
      TAG: $(date +%s)

    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        docker build . --file docker/app/Dockerfile --tag ghcr.io/LiZeC123/smart-todo-app
        docker build . --file docker/web/Dockerfile --tag ghcr.io/LiZeC123/smart-todo-web
    
    - name: Build the SmartTodo Web Image
      
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker Image to Github Packages
      run: |
        docker push ghcr.io/LiZeC123/smart-todo-app
        docker push ghcr.io/LiZeC123/smart-todo-app
