name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.13

    - name: Generate coverage report
      run: |
        cp -r config backend/config
        cd backend
        mkdir data
        pip install -r requirements.txt
        pip install pytest pytest-cov   
        pytest --cov=./ --cov-report=xml  

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./app/coverage.xml
        flags: unittests

  build:
    runs-on: ubuntu-latest
    needs: test
    
    permissions:
      contents: read
      packages: write
    
    env:
      TAG: $(date +%s)

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Image
      run: docker build . --file docker/Dockerfile --tag ghcr.io/lizec123/smart-todo
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker Image to Github Packages
      run: docker push ghcr.io/lizec123/smart-todo
        
